# Generated by Django 3.0.6 on 2024-11-14 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0006_invoicefilelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceedhistory',
            name='ed_user',
            field=models.ForeignKey(blank=True, db_column='ed_user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoicefilelog',
            name='ifl_invoice',
            field=models.ForeignKey(blank=True, db_column='ifl_invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.Invoice'),
        ),
    ]
