# Generated by Django 3.0.6 on 2024-11-14 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190530_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_key',
            field=models.ForeignKey(db_column='role_key', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Role'),
        ),
    ]
